/*
  Automatically generated by Autodist 1.4.  Do not edit.

  Generated: Tue May 13 09:45:18 EEST 2014 by priikone
  Distribution: Client
  License: 
*/

#ifndef _SILC_DISTDEFS_H
#define _SILC_DISTDEFS_H

#define SILC_DIST_APPS 1
#define SILC_DIST_ASN1 1
#define SILC_DIST_CLIENT 1
#define SILC_DIST_CLIENTLIB 1
#define SILC_DIST_COMPILER 1
#define SILC_DIST_CRYPTO 1
#define SILC_DIST_DOC 1
#define SILC_DIST_IDCACHE 1
#define SILC_DIST_INCLUDES 1
#define SILC_DIST_LIB 1
#define SILC_DIST_MATH 1
#define SILC_DIST_SFTP 1
#define SILC_DIST_SILC 1
#define SILC_DIST_SKR 1
#define SILC_DIST_TMA 1
#define SILC_DIST_VCARD 1

#endif /* _SILC_DISTDEFS_H */
